### ISSUE TITLE
Scrolling down the list of Play Next causes Playnite to Crash

### ISSUE THREAD

**Issue by Jhanlon95** [SparrowBrain/Playnite.PlayNext#1]
Hi, installed the add-on as it looked like a nice little extra to include. When I click on the icon on the sidebar, put the games into list mode and begin to scroll down the list eventually Playnite crashes and closes

![Playnite DesktopApp_SglX00SeLt](https://user-images.githubusercontent.com/11045596/225768298-fd372324-ef2f-414f-9f31-69182f78ee7b.gif)

**Comment by SparrowBrain** [comment]
Hey, thanks for reporting!

I've had this bug before, it's weird it popped up again. I have a hunch, where I made a mistake with assumptions.
Will fix it as soon as I get some time.

**Comment by SparrowBrain** [comment]
Should be fixed in v1.0.1. Can you verify, if it works for you?

**Comment by Jhanlon95** [comment]
I can confirm that it is now fixed for me, thank you for such a quick turn around on this!
