### ISSUE TITLE
Feature request: filter games based on completion state

### ISSUE THREAD

**Issue by HerrKnarz** [SparrowBrain/Playnite.PlayNext#2]
The addon looks very promising, but it unfortunately has one big flaw: It shows games, that I already have beaten. At the moment at least 60% of the suggested games are already beaten games for me. It would be great if you could filter the completion state to only show games that have specific states or at least filter out certain states like "beaten", "abandoned" or "completed".

It also would be great if you could put different weights on different completion states. For example I have one with games I really want to play and another with games, that I'll maybe play sometime. It would be great if the games from the first list could be weighted higher than the second.

**Comment by SparrowBrain** [comment]
Hey, thanks for the feature request - the first one is actually something I planned to do.

Right now unplayed games are selected by checking for zero playtime, but you should really be able to do it by completion status.

The second is a bit trickier, I will think what's the best way to do it.

**Comment by HerrKnarz** [comment]
You could add all completion statuses to a list view that has a check box to toggle which will be considered, and a slider to set the weight like with the other properties you have already.
