### ISSUE TITLE
[Enhancement] Option for horizontal StartPage title

### ISSUE THREAD

**Issue by chocolatechipcats** [SparrowBrain/Playnite.PlayNext#4]
Hi, I like the plugin!

A request regarding the StartPage view. The title is vertical. If the option was available, I'd prefer it horizontal in order to match new games shelf and also hopefully fix the slight misalignment:

![image](https://user-images.githubusercontent.com/47759676/234538775-aa29d940-9bfd-4d13-8960-c5e06106e309.png)

Thanks in advance.

**Comment by SparrowBrain** [comment]
Great catch! Will implement this, but probably not very soon. Quite busy atm!

**Comment by chocolatechipcats** [comment]
The recent StartPage addon added the option to show a view label, so hiding it entirely could be another option. Thanks. :)

**Comment by SparrowBrain** [comment]
Hey @chocolatechipcats! I've released an update with an ability to show horizontal label, or hide it completely. Tried solving the alignment issues the best I could, but it can still be wonky sometimes depending on the situation.

Hope this works for you! :)
