### ISSUE TITLE
[Enhancement] Documentation of how weighting works

### ISSUE THREAD

**Issue by chocolatechipcats** [SparrowBrain/Playnite.PlayNext#9]
Some more documentation of the various weighting options in the settings would be helpful. 

In specific:
I have no idea what Attribute Calculation Weights > Recent Order does,
I only have a vague idea of Game Score Calculation Weights > Release Year, except that it changes the games to different ones.

Thanks in advance!

**Comment by SparrowBrain** [comment]
Good point. I'll try to update the docs. For now:
Left part of the settings assigns scores to various attributes (genres, features, etc.) depending on games you've played. It's weighted between total playtime, recent playtime (GameActivity extension) and recent order (poor man's substitution to recent playtime).
Right part calculates the actual game scores. It uses these attribute scores we received and some additional score calculators (like release year, critics score, etc.)

* Recent Order - basically it looks at the games you've played within recent days (default 2 weeks). Then orders them from most recent to oldest played game. Most recent game's attributes get 100 (actually 100 divided by game's attribute count) score. Oldest game's attributes get 0. Then it's all weighted, summed up and normalized with other two setting's results.
* Release Year - it prioritizes games with a preferred release year. It can be configured to be current (2023) or a specific. Then basically every game gets a score assigned depending on how close it's release year is to the preferred. If the year matches, game gets 100 score. If the release year is the maximum furthest (within your library) it gets score 0. Of course then this gets weighted and added to other attribute scores.

I hope this helps. If not, let me know, I'll try to rephrase after a good night's sleep.

Additionally I would like to improve the UI to give more info about the algorithm, but that will require a big rewrite, so it's not gonna happen soon.
